// <auto-generated />
using AssignmentApp.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AssignmentApp.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220513114626_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AssignmentApp.Core.Entities.Match", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatchDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatchTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sport")
                        .HasColumnType("int");

                    b.Property<string>("TeamA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamB")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            Description = "OSFP-PAO",
                            MatchDate = "12/05/2022",
                            MatchTime = "12:00",
                            Sport = 1,
                            TeamA = "OSFP",
                            TeamB = "PAO"
                        });
                });

            modelBuilder.Entity("AssignmentApp.Core.Entities.MatchOdds", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("MatchID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Odd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Specifier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MatchID")
                        .IsUnique();

                    b.ToTable("MatchOdds");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            MatchID = 1L,
                            Odd = 1.5m,
                            Specifier = "X"
                        });
                });

            modelBuilder.Entity("AssignmentApp.Core.Entities.MatchOdds", b =>
                {
                    b.HasOne("AssignmentApp.Core.Entities.Match", "Match")
                        .WithOne("MatchOdds")
                        .HasForeignKey("AssignmentApp.Core.Entities.MatchOdds", "MatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
